spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml